[tool.poetry]
name = "speech-to-text"
version = "0.1.0"
description = ""
authors = ["nishio.n0522 <nishio.n0522@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.40.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
